CITIES_OPTIONS=[
    ("Abu Hammad","Abu Hammad"),
    ("Al Mahallah al Kubra","Al Mahallah al Kubra"),
    ("Al Mansurah","Al Mansurah"),
    ("Al Marj","Al Marj"),
    ("Alexandria","Alexandria"),
    ("Almazah","Almazah"),
    ("Ar Rawdah","Ar Rawdah"),
    ("Assiut","Assiut"),
    ("Az Zamalik","Az Zamalik"),
    ("Badr","Badr"),
    ("Banha","Banha"),
    ("Bani Suwayf","Bani Suwayf"),
    ("Cairo","Cairo"),
    ("Damietta","Damietta"),
    ("Faraskur","Faraskur"),
    ("Flaminj","Flaminj"),
    ("Giza","Giza"),
    ("Heliopolis","Heliopolis"),
    ("Helwan","Helwan"),
    ("Hurghada","Hurghada"),
    ("Ismailia","Ismailia"),
    ("Kafr ash Shaykh","Kafr ash Shaykh"),
    ("Luxor","Luxor"),
    ("Madinat an Nasr","Madinat an Nasr"),
    ("Madinat as Sadis min Uktubar","Madinat as Sadis min Uktubar"),
    ("Minya","Minya"),
    ("Nasr","Nasr"),
    ("New Cairo","New Cairo"),
    ("Port Said","Port Said"),
    ("Rafah","Rafah"),
    ("Ramsis","Ramsis"),
    ("Sadat","Sadat"),
    ("Shirbin","Shirbin"),
    ("Shubra","Shubra"),
    ("Sohag","Sohag"),
    ("Suez","Suez"),
    ("Tanta","Tanta"),
    ("Toukh","Toukh"),
    ("Zagazig","Zagazig"),
]