version: '3.10'

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=kantan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P0StgreS
    ports:
      - 5435:5432
    expose:
      - 5435

  django:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/Kantan_Back
    command: >
            sh -c "python backend/manage.py collectstatic --noinput &&
                   python backend/manage.py makemigrations &&
                   python backend/manage.py migrate &&

                   python backend/manage.py runserver 0.0.0.0:2000"
    restart: always
    expose:
      - 2000
    ports:
      - 2000:2000
    environment:
      - DB_HOST=db
      - POSTGRES_NAME=kantan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P0StgreS
      - POSTGRES_PORT=5432
    depends_on:
      - db
